---
- name: install and update python virtual environment
  hosts: testServer 
  remote_user: cyborg
  become: yes

  vars_files:
    - venv_vars.yml

  tasks:
  - name: Enable EPEL Repository on CentOS 7
    yum: name=epel-release state=present

  - name: Install python packages
    yum: name={{item}} state=present
    with_items:
      - python3
      - python3-devel
      - python3-pip
      - python36-virtualenv

  - name: Install virtualenv module
    pip: 
      name: virtualenv
      state: present
      executable: pip3

  - name: Create python3 virtual environment folder
    file: name=/opt/python state=directory

  - name: Initiate virtualenv
    pip:
      name: "{{ venv }}"
      virtualenv: /opt/python/{{ venv }}
      virtualenv_command: /usr/bin/python3.6 -m venv
        #executable: pip3
      
