# This is a basic workflow to help you get started with Actions

name: Install puthon venv on target with Ansible playbook

# Controls when the workflow will run
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
    
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: virtualenv.yml
          # Optional, directory where playbooks live
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [testServer]
            192.168.122.160

